# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\01 Github\02-Python\01 CN2\Socket\Server\server1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 169)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(220, 20, 191, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(130, 40, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(130, 60, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(130, 80, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 100, 91, 16))
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(130, 100, 91, 16))
        self.label_17.setObjectName("label_17")
        self.btnOpenServer = QtWidgets.QPushButton(Dialog)
        self.btnOpenServer.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.btnOpenServer.setObjectName("btnOpenServer")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Server - Bài tập Mạng máy tính"))
        self.groupBox.setTitle(_translate("Dialog", "Danh sách tham gia"))
        self.label.setText(_translate("Dialog", "01 Nguyễn Hải Hà"))
        self.label_2.setText(_translate("Dialog", "21880031"))
        self.label_3.setText(_translate("Dialog", "01 Nguyen Hai Ha"))
        self.label_4.setText(_translate("Dialog", "21880031"))
        self.label_5.setText(_translate("Dialog", "01 Nguyen Hai Ha"))
        self.label_6.setText(_translate("Dialog", "21880031"))
        self.label_14.setText(_translate("Dialog", "01 Nguyen Hai Ha"))
        self.label_15.setText(_translate("Dialog", "21880031"))
        self.label_16.setText(_translate("Dialog", "01 Nguyen Hai Ha"))
        self.label_17.setText(_translate("Dialog", "21880031"))
        self.btnOpenServer.setText(_translate("Dialog", "Mở Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
